//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.21 at 11:24:30 PM PDT 
//


package io.github.ericdriggs.reportcard.xml.surefire;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;

import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the io.github.ericdriggs.reportcard.gen.surefire package.
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TestsuiteTestcaseSkipped_QNAME = new QName("", "skipped");
    private final static QName _TestsuiteTestcaseError_QNAME = new QName("", "error");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: io.github.ericdriggs.reportcard.gen.surefire
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Testsuite }
     * 
     */
    public Testsuite createTestsuite() {
        return new Testsuite();
    }

    /**
     * Create an instance of {@link Testcase }
     * 
     */
    public Testcase createTestsuiteTestcase() {
        return new Testcase();
    }

    /**
     * Create an instance of {@link Properties }
     * 
     */
    public Properties createTestsuiteProperties() {
        return new Properties();
    }

    /**
     * Create an instance of {@link Failure }
     * 
     */
    public Failure createTestsuiteTestcaseFailure() {
        return new Failure();
    }

    /**
     * Create an instance of {@link RerunFailure }
     * 
     */
    public RerunFailure createTestsuiteTestcaseRerunFailure() {
        return new RerunFailure();
    }

    /**
     * Create an instance of {@link FlakyFailure }
     * 
     */
    public FlakyFailure createTestsuiteTestcaseFlakyFailure() {
        return new FlakyFailure();
    }

    /**
     * Create an instance of {@link Skipped }
     * 
     */
    public Skipped createTestsuiteTestcaseSkipped() {
        return new Skipped();
    }

    /**
     * Create an instance of {@link Error }
     * 
     */
    public Error createTestsuiteTestcaseError() {
        return new Error();
    }

    /**
     * Create an instance of {@link RerunError }
     * 
     */
    public RerunError createTestsuiteTestcaseRerunError() {
        return new RerunError();
    }

    /**
     * Create an instance of {@link FlakyError }
     * 
     */
    public FlakyError createTestsuiteTestcaseFlakyError() {
        return new FlakyError();
    }

    /**
     * Create an instance of {@link Property }
     * 
     */
    public Property createTestsuitePropertiesProperty() {
        return new Property();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Skipped }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "skipped", scope = Testcase.class)
    public JAXBElement<Skipped> createTestsuiteTestcaseSkipped(Skipped value) {
        return new JAXBElement<>(_TestsuiteTestcaseSkipped_QNAME, Skipped.class, Testcase.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Error }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "error", scope = Testcase.class)
    public JAXBElement<Error> createTestsuiteTestcaseError(Error value) {
        return new JAXBElement<>(_TestsuiteTestcaseError_QNAME, Error.class, Testcase.class, value);
    }

}
