/*
 * This file is generated by jOOQ.
 */
package io.github.ericdriggs.reportcard.dto;


import lombok.Builder;
import lombok.Data;
import lombok.experimental.SuperBuilder;

import java.io.Serial;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

@Data
@SuperBuilder(builderMethodName = "testCaseBuilder", toBuilder = true)
public class TestCase implements Serializable {

    public TestCase() {
    }

    @Serial
    private static final long serialVersionUID = -3938894842199056311L;

    protected Long testCaseId;
    protected Long testSuiteFk;
    protected String name;
    protected String className;
    protected BigDecimal time;
    protected Byte testStatusFk;
    protected String assertions;
    protected String systemOut;
    protected String systemErr;

    @Builder.Default
    protected List<String> tags = new ArrayList<>();
}
