/*
 * This file is generated by jOOQ.
 */
package io.github.ericdriggs.reportcard.dto;

import lombok.Builder;
import lombok.Data;
import lombok.experimental.SuperBuilder;

import java.io.Serial;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

@SuperBuilder(builderMethodName = "testSuiteBuilder", toBuilder = true)
@Data
public class TestSuite implements Serializable {

    public TestSuite() {

    }

    @Serial
    private static final long serialVersionUID = -200588524670176256L;

    private Long testSuiteId;
    private Long testResultFk;
    private String name;
    private Integer tests;
    private Integer skipped;
    private Integer error;
    private Integer failure;
    private BigDecimal time;
    private String packageName;
    private String group;
    private String properties;
    private Boolean isSuccess;
    private Boolean hasSkip;
    private String systemOut;
    private String systemErr;

    @Builder.Default
    private List<String> tags = new ArrayList<>();

}

