//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.21 at 11:18:04 PM PDT 
//


package io.github.ericdriggs.reportcard.xml.junit;

import lombok.*;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;
import java.math.BigDecimal;
import java.util.List;


/**
 * Contains the results of executing a testsuite
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "testsuite", propOrder = {
        "properties",
        "testcase",
        "system_out",
        "system_err"
})
@XmlRootElement(name = "testsuite")
@NoArgsConstructor
@AllArgsConstructor
@Builder(builderMethodName = "builderForTestsuite")
@Data
public class Testsuite {

    @XmlElement(required = true)
    protected Properties properties;
    protected List<Testcase> testcase;

    @XmlElement(name = "system-out")
    protected String system_out;

    @XmlAttribute(name = "system-err")
    protected String system_err;

    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlAttribute(name = "name", required = true)
    protected String name;

    @XmlAttribute(name = "tests", required = true)
    protected int tests;

    @XmlAttribute(name = "failures")
    protected int failures;

    @XmlAttribute(name = "errors")
    protected int errors;

    @XmlAttribute(name = "time")
    protected BigDecimal time;

    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlAttribute(name = "disabled")
    protected String disabled;

    @XmlAttribute(name = "skipped")
    protected Integer skipped;


    @XmlAttribute(name = "timestamp")
    protected XMLGregorianCalendar timestamp;

    @XmlAttribute(name = "hostname")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String hostname;

    @XmlAttribute(name = "id")
    protected int id;

    @XmlAttribute(name = "package")
    protected String _package;

}
