/*
 * This file is generated by jOOQ.
 */
package io.github.ericdriggs.reportcard.pojos;

import lombok.Data;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.List;
import java.util.Properties;

@Data
public class TestSuite implements Serializable {

    private static final long serialVersionUID = -200588524670176256L;

    private Long testSuiteId;
    private Long testResultFk;
    private String name;
    private Integer tests;
    private Integer skipped;
    private Integer error;
    private Integer failure;
    private BigDecimal time;
    private String package_;
    private String group;
    private String properties;
    private Boolean isSuccess;
    private Boolean hasSkip;

    public String getPackage() {
        return package_;
    }

    public TestSuite setPackage(String package_) {
        this.package_ = package_;
        return this;
    }
}

