//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.21 at 11:26:30 PM PDT 
//


package com.ericdriggs.reportcard.xml.testng;

import lombok.*;

import javax.xml.bind.annotation.*;
import java.util.List;


/**
 * <p>Java class for any complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="any"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;any maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "any", propOrder = {
    "content"
})
@XmlSeeAlso({
    SuiteFile.class,
    Parameter.class,
    Script.class,
    SelectorClass.class,
    Listener.class,
    Group.class,
    Exclude.class,
    Include.class
})
@NoArgsConstructor
@AllArgsConstructor
@Builder(builderMethodName = "builderForAny")
@Data
public class Any {

    @XmlMixed
    @XmlAnyElement(lax = true)
    protected List<Object> content;
}
