/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.ericdriggs.reportcard.client.api;

import java.io.File;
import com.ericdriggs.reportcard.client.api.ReportMetaData;
import com.ericdriggs.reportcard.client.api.TestResult;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ReportControllerApi
 */
@Ignore
public class ReportControllerApiTest {

    private final ReportControllerApi api = new ReportControllerApi();

    
    /**
     * postXmlJunit
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postXmlJunitUsingPOSTTest() {
        File file = null;
        ReportMetaData reportMetatData = null;
        TestResult response = api.postXmlJunitUsingPOST(file, reportMetatData);

        // TODO: test validations
    }
    
    /**
     * postXmlSurefire
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postXmlSurefireUsingPOSTTest() {
        List<File> files = null;
        ReportMetaData reportMetatData = null;
        TestResult response = api.postXmlSurefireUsingPOST(files, reportMetatData);

        // TODO: test validations
    }
    
    /**
     * postXml
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postXmlUsingPOSTTest() {
        List<File> files = null;
        ReportMetaData reportMetatData = null;
        TestResult response = api.postXmlUsingPOST(files, reportMetatData);

        // TODO: test validations
    }
    
}
