//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.21 at 11:26:30 PM PDT 
//


package com.ericdriggs.reportcard.xml.testng.suite;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ericdriggs.reportcard.gen.testng package.
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ericdriggs.reportcard.gen.testng
     *
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Suite }
     *
     */
    public Suite createSuite() {
        return new Suite();
    }

    /**
     * Create an instance of {@link Groups }
     *
     */
    public Groups createGroups() {
        return new Groups();
    }

    /**
     * Create an instance of {@link Define }
     *
     */
    public Define createDefine() {
        return new Define();
    }

    /**
     * Create an instance of {@link Include }
     *
     */
    public Include createInclude() {
        return new Include();
    }

    /**
     * Create an instance of {@link Any }
     *
     */
    public Any createAny() {
        return new Any();
    }

    /**
     * Create an instance of {@link Run }
     *
     */
    public Run createRun() {
        return new Run();
    }

    /**
     * Create an instance of {@link Exclude }
     *
     */
    public Exclude createExclude() {
        return new Exclude();
    }

    /**
     * Create an instance of {@link Dependencies }
     *
     */
    public Dependencies createDependencies() {
        return new Dependencies();
    }

    /**
     * Create an instance of {@link Group }
     *
     */
    public Group createGroup() {
        return new Group();
    }

    /**
     * Create an instance of {@link Listeners }
     *
     */
    public Listeners createListeners() {
        return new Listeners();
    }

    /**
     * Create an instance of {@link Listener }
     *
     */
    public Listener createListener() {
        return new Listener();
    }

    /**
     * Create an instance of {@link Packages }
     *
     */
    public Packages createPackages() {
        return new Packages();
    }

    /**
     * Create an instance of {@link Package }
     *
     */
    public Package createPackage() {
        return new Package();
    }

    /**
     * Create an instance of {@link Test }
     *
     */
    public Test createTest() {
        return new Test();
    }

    /**
     * Create an instance of {@link MethodSelectors }
     *
     */
    public MethodSelectors createMethodSelectors() {
        return new MethodSelectors();
    }

    /**
     * Create an instance of {@link MethodSelector }
     *
     */
    public MethodSelector createMethodSelector() {
        return new MethodSelector();
    }

    /**
     * Create an instance of {@link SelectorClass }
     *
     */
    public SelectorClass createSelectorClass() {
        return new SelectorClass();
    }

    /**
     * Create an instance of {@link Script }
     *
     */
    public Script createScript() {
        return new Script();
    }

    /**
     * Create an instance of {@link Parameter }
     *
     */
    public Parameter createParameter() {
        return new Parameter();
    }

    /**
     * Create an instance of {@link Classes }
     *
     */
    public Classes createClasses() {
        return new Classes();
    }

//    /**
//     * Create an instance of {@link java.lang.Class }
//     *
//     */
//    public java.lang.Class createClass() {
//        return new java.lang.Class();
//    }

    /**
     * Create an instance of {@link Methods }
     *
     */
    public Methods createMethods() {
        return new Methods();
    }

    /**
     * Create an instance of {@link SuiteFiles }
     *
     */
    public SuiteFiles createSuiteFiles() {
        return new SuiteFiles();
    }

    /**
     * Create an instance of {@link SuiteFile }
     *
     */
    public SuiteFile createSuiteFile() {
        return new SuiteFile();
    }

}
