//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.21 at 11:18:04 PM PDT 
//


package com.ericdriggs.ragnarok.xml.junit;

import lombok.*;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;
import java.math.BigDecimal;
import java.util.List;


/**
 * Contains the results of exexuting a testsuite
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "testsuite", propOrder = {
        "properties",
        "testcase",
        "systemOut",
        "systemErr"
})
@XmlSeeAlso({
        Testsuites.Testsuite.class
})
@NoArgsConstructor
@AllArgsConstructor
@Builder(builderMethodName = "builderForTestsuite")
@Data
public class Testsuite {

    @XmlElement(required = true)
    protected Properties properties;
    protected List<Testcase> testcase;
    @XmlElement(name = "system-out", required = true)
    protected String systemOut;
    @XmlElement(name = "system-err", required = true)
    protected String systemErr;
    @XmlAttribute(name = "name", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String name;
    @XmlAttribute(name = "timestamp", required = true)
    protected XMLGregorianCalendar timestamp;
    @XmlAttribute(name = "hostname", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String hostname;
    @XmlAttribute(name = "tests", required = true)
    protected int tests;
    @XmlAttribute(name = "failures", required = true)
    protected int failures;
    @XmlAttribute(name = "errors", required = true)
    protected int errors;
    @XmlAttribute(name = "skipped")
    protected Integer skipped;
    @XmlAttribute(name = "time", required = true)
    protected BigDecimal time;


}
