/*
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ReportMetaData struct for ReportMetaData
type ReportMetaData struct {
	Org *string `json:"org,omitempty"`
	Repo *string `json:"repo,omitempty"`
	Branch *string `json:"branch,omitempty"`
	Sha *string `json:"sha,omitempty"`
	HostApplicationPipeline *HostApplicationPipeline `json:"hostApplicationPipeline,omitempty"`
	ExternalExecutionId *string `json:"externalExecutionId,omitempty"`
	Stage *string `json:"stage,omitempty"`
	ExternalLinks *map[string]string `json:"externalLinks,omitempty"`
}

// NewReportMetaData instantiates a new ReportMetaData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReportMetaData() *ReportMetaData {
	this := ReportMetaData{}
	return &this
}

// NewReportMetaDataWithDefaults instantiates a new ReportMetaData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReportMetaDataWithDefaults() *ReportMetaData {
	this := ReportMetaData{}
	return &this
}

// GetOrg returns the Org field value if set, zero value otherwise.
func (o *ReportMetaData) GetOrg() string {
	if o == nil || o.Org == nil {
		var ret string
		return ret
	}
	return *o.Org
}

// GetOrgOk returns a tuple with the Org field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReportMetaData) GetOrgOk() (*string, bool) {
	if o == nil || o.Org == nil {
		return nil, false
	}
	return o.Org, true
}

// HasOrg returns a boolean if a field has been set.
func (o *ReportMetaData) HasOrg() bool {
	if o != nil && o.Org != nil {
		return true
	}

	return false
}

// SetOrg gets a reference to the given string and assigns it to the Org field.
func (o *ReportMetaData) SetOrg(v string) {
	o.Org = &v
}

// GetRepo returns the Repo field value if set, zero value otherwise.
func (o *ReportMetaData) GetRepo() string {
	if o == nil || o.Repo == nil {
		var ret string
		return ret
	}
	return *o.Repo
}

// GetRepoOk returns a tuple with the Repo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReportMetaData) GetRepoOk() (*string, bool) {
	if o == nil || o.Repo == nil {
		return nil, false
	}
	return o.Repo, true
}

// HasRepo returns a boolean if a field has been set.
func (o *ReportMetaData) HasRepo() bool {
	if o != nil && o.Repo != nil {
		return true
	}

	return false
}

// SetRepo gets a reference to the given string and assigns it to the Repo field.
func (o *ReportMetaData) SetRepo(v string) {
	o.Repo = &v
}

// GetBranch returns the Branch field value if set, zero value otherwise.
func (o *ReportMetaData) GetBranch() string {
	if o == nil || o.Branch == nil {
		var ret string
		return ret
	}
	return *o.Branch
}

// GetBranchOk returns a tuple with the Branch field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReportMetaData) GetBranchOk() (*string, bool) {
	if o == nil || o.Branch == nil {
		return nil, false
	}
	return o.Branch, true
}

// HasBranch returns a boolean if a field has been set.
func (o *ReportMetaData) HasBranch() bool {
	if o != nil && o.Branch != nil {
		return true
	}

	return false
}

// SetBranch gets a reference to the given string and assigns it to the Branch field.
func (o *ReportMetaData) SetBranch(v string) {
	o.Branch = &v
}

// GetSha returns the Sha field value if set, zero value otherwise.
func (o *ReportMetaData) GetSha() string {
	if o == nil || o.Sha == nil {
		var ret string
		return ret
	}
	return *o.Sha
}

// GetShaOk returns a tuple with the Sha field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReportMetaData) GetShaOk() (*string, bool) {
	if o == nil || o.Sha == nil {
		return nil, false
	}
	return o.Sha, true
}

// HasSha returns a boolean if a field has been set.
func (o *ReportMetaData) HasSha() bool {
	if o != nil && o.Sha != nil {
		return true
	}

	return false
}

// SetSha gets a reference to the given string and assigns it to the Sha field.
func (o *ReportMetaData) SetSha(v string) {
	o.Sha = &v
}

// GetHostApplicationPipeline returns the HostApplicationPipeline field value if set, zero value otherwise.
func (o *ReportMetaData) GetHostApplicationPipeline() HostApplicationPipeline {
	if o == nil || o.HostApplicationPipeline == nil {
		var ret HostApplicationPipeline
		return ret
	}
	return *o.HostApplicationPipeline
}

// GetHostApplicationPipelineOk returns a tuple with the HostApplicationPipeline field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReportMetaData) GetHostApplicationPipelineOk() (*HostApplicationPipeline, bool) {
	if o == nil || o.HostApplicationPipeline == nil {
		return nil, false
	}
	return o.HostApplicationPipeline, true
}

// HasHostApplicationPipeline returns a boolean if a field has been set.
func (o *ReportMetaData) HasHostApplicationPipeline() bool {
	if o != nil && o.HostApplicationPipeline != nil {
		return true
	}

	return false
}

// SetHostApplicationPipeline gets a reference to the given HostApplicationPipeline and assigns it to the HostApplicationPipeline field.
func (o *ReportMetaData) SetHostApplicationPipeline(v HostApplicationPipeline) {
	o.HostApplicationPipeline = &v
}

// GetExternalExecutionId returns the ExternalExecutionId field value if set, zero value otherwise.
func (o *ReportMetaData) GetExternalExecutionId() string {
	if o == nil || o.ExternalExecutionId == nil {
		var ret string
		return ret
	}
	return *o.ExternalExecutionId
}

// GetExternalExecutionIdOk returns a tuple with the ExternalExecutionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReportMetaData) GetExternalExecutionIdOk() (*string, bool) {
	if o == nil || o.ExternalExecutionId == nil {
		return nil, false
	}
	return o.ExternalExecutionId, true
}

// HasExternalExecutionId returns a boolean if a field has been set.
func (o *ReportMetaData) HasExternalExecutionId() bool {
	if o != nil && o.ExternalExecutionId != nil {
		return true
	}

	return false
}

// SetExternalExecutionId gets a reference to the given string and assigns it to the ExternalExecutionId field.
func (o *ReportMetaData) SetExternalExecutionId(v string) {
	o.ExternalExecutionId = &v
}

// GetStage returns the Stage field value if set, zero value otherwise.
func (o *ReportMetaData) GetStage() string {
	if o == nil || o.Stage == nil {
		var ret string
		return ret
	}
	return *o.Stage
}

// GetStageOk returns a tuple with the Stage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReportMetaData) GetStageOk() (*string, bool) {
	if o == nil || o.Stage == nil {
		return nil, false
	}
	return o.Stage, true
}

// HasStage returns a boolean if a field has been set.
func (o *ReportMetaData) HasStage() bool {
	if o != nil && o.Stage != nil {
		return true
	}

	return false
}

// SetStage gets a reference to the given string and assigns it to the Stage field.
func (o *ReportMetaData) SetStage(v string) {
	o.Stage = &v
}

// GetExternalLinks returns the ExternalLinks field value if set, zero value otherwise.
func (o *ReportMetaData) GetExternalLinks() map[string]string {
	if o == nil || o.ExternalLinks == nil {
		var ret map[string]string
		return ret
	}
	return *o.ExternalLinks
}

// GetExternalLinksOk returns a tuple with the ExternalLinks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReportMetaData) GetExternalLinksOk() (*map[string]string, bool) {
	if o == nil || o.ExternalLinks == nil {
		return nil, false
	}
	return o.ExternalLinks, true
}

// HasExternalLinks returns a boolean if a field has been set.
func (o *ReportMetaData) HasExternalLinks() bool {
	if o != nil && o.ExternalLinks != nil {
		return true
	}

	return false
}

// SetExternalLinks gets a reference to the given map[string]string and assigns it to the ExternalLinks field.
func (o *ReportMetaData) SetExternalLinks(v map[string]string) {
	o.ExternalLinks = &v
}

func (o ReportMetaData) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Org != nil {
		toSerialize["org"] = o.Org
	}
	if o.Repo != nil {
		toSerialize["repo"] = o.Repo
	}
	if o.Branch != nil {
		toSerialize["branch"] = o.Branch
	}
	if o.Sha != nil {
		toSerialize["sha"] = o.Sha
	}
	if o.HostApplicationPipeline != nil {
		toSerialize["hostApplicationPipeline"] = o.HostApplicationPipeline
	}
	if o.ExternalExecutionId != nil {
		toSerialize["externalExecutionId"] = o.ExternalExecutionId
	}
	if o.Stage != nil {
		toSerialize["stage"] = o.Stage
	}
	if o.ExternalLinks != nil {
		toSerialize["externalLinks"] = o.ExternalLinks
	}
	return json.Marshal(toSerialize)
}

type NullableReportMetaData struct {
	value *ReportMetaData
	isSet bool
}

func (v NullableReportMetaData) Get() *ReportMetaData {
	return v.value
}

func (v *NullableReportMetaData) Set(val *ReportMetaData) {
	v.value = val
	v.isSet = true
}

func (v NullableReportMetaData) IsSet() bool {
	return v.isSet
}

func (v *NullableReportMetaData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReportMetaData(val *ReportMetaData) *NullableReportMetaData {
	return &NullableReportMetaData{value: val, isSet: true}
}

func (v NullableReportMetaData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReportMetaData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


