/*
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// Context struct for Context
type Context struct {
	ContextId *int64 `json:"contextId,omitempty"`
	ShaFk *int64 `json:"shaFk,omitempty"`
	Host *string `json:"host,omitempty"`
	Application *string `json:"application,omitempty"`
	Pipeline *string `json:"pipeline,omitempty"`
}

// NewContext instantiates a new Context object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewContext() *Context {
	this := Context{}
	return &this
}

// NewContextWithDefaults instantiates a new Context object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewContextWithDefaults() *Context {
	this := Context{}
	return &this
}

// GetContextId returns the ContextId field value if set, zero value otherwise.
func (o *Context) GetContextId() int64 {
	if o == nil || o.ContextId == nil {
		var ret int64
		return ret
	}
	return *o.ContextId
}

// GetContextIdOk returns a tuple with the ContextId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Context) GetContextIdOk() (*int64, bool) {
	if o == nil || o.ContextId == nil {
		return nil, false
	}
	return o.ContextId, true
}

// HasContextId returns a boolean if a field has been set.
func (o *Context) HasContextId() bool {
	if o != nil && o.ContextId != nil {
		return true
	}

	return false
}

// SetContextId gets a reference to the given int64 and assigns it to the ContextId field.
func (o *Context) SetContextId(v int64) {
	o.ContextId = &v
}

// GetShaFk returns the ShaFk field value if set, zero value otherwise.
func (o *Context) GetShaFk() int64 {
	if o == nil || o.ShaFk == nil {
		var ret int64
		return ret
	}
	return *o.ShaFk
}

// GetShaFkOk returns a tuple with the ShaFk field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Context) GetShaFkOk() (*int64, bool) {
	if o == nil || o.ShaFk == nil {
		return nil, false
	}
	return o.ShaFk, true
}

// HasShaFk returns a boolean if a field has been set.
func (o *Context) HasShaFk() bool {
	if o != nil && o.ShaFk != nil {
		return true
	}

	return false
}

// SetShaFk gets a reference to the given int64 and assigns it to the ShaFk field.
func (o *Context) SetShaFk(v int64) {
	o.ShaFk = &v
}

// GetHost returns the Host field value if set, zero value otherwise.
func (o *Context) GetHost() string {
	if o == nil || o.Host == nil {
		var ret string
		return ret
	}
	return *o.Host
}

// GetHostOk returns a tuple with the Host field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Context) GetHostOk() (*string, bool) {
	if o == nil || o.Host == nil {
		return nil, false
	}
	return o.Host, true
}

// HasHost returns a boolean if a field has been set.
func (o *Context) HasHost() bool {
	if o != nil && o.Host != nil {
		return true
	}

	return false
}

// SetHost gets a reference to the given string and assigns it to the Host field.
func (o *Context) SetHost(v string) {
	o.Host = &v
}

// GetApplication returns the Application field value if set, zero value otherwise.
func (o *Context) GetApplication() string {
	if o == nil || o.Application == nil {
		var ret string
		return ret
	}
	return *o.Application
}

// GetApplicationOk returns a tuple with the Application field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Context) GetApplicationOk() (*string, bool) {
	if o == nil || o.Application == nil {
		return nil, false
	}
	return o.Application, true
}

// HasApplication returns a boolean if a field has been set.
func (o *Context) HasApplication() bool {
	if o != nil && o.Application != nil {
		return true
	}

	return false
}

// SetApplication gets a reference to the given string and assigns it to the Application field.
func (o *Context) SetApplication(v string) {
	o.Application = &v
}

// GetPipeline returns the Pipeline field value if set, zero value otherwise.
func (o *Context) GetPipeline() string {
	if o == nil || o.Pipeline == nil {
		var ret string
		return ret
	}
	return *o.Pipeline
}

// GetPipelineOk returns a tuple with the Pipeline field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Context) GetPipelineOk() (*string, bool) {
	if o == nil || o.Pipeline == nil {
		return nil, false
	}
	return o.Pipeline, true
}

// HasPipeline returns a boolean if a field has been set.
func (o *Context) HasPipeline() bool {
	if o != nil && o.Pipeline != nil {
		return true
	}

	return false
}

// SetPipeline gets a reference to the given string and assigns it to the Pipeline field.
func (o *Context) SetPipeline(v string) {
	o.Pipeline = &v
}

func (o Context) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.ContextId != nil {
		toSerialize["contextId"] = o.ContextId
	}
	if o.ShaFk != nil {
		toSerialize["shaFk"] = o.ShaFk
	}
	if o.Host != nil {
		toSerialize["host"] = o.Host
	}
	if o.Application != nil {
		toSerialize["application"] = o.Application
	}
	if o.Pipeline != nil {
		toSerialize["pipeline"] = o.Pipeline
	}
	return json.Marshal(toSerialize)
}

type NullableContext struct {
	value *Context
	isSet bool
}

func (v NullableContext) Get() *Context {
	return v.value
}

func (v *NullableContext) Set(val *Context) {
	v.value = val
	v.isSet = true
}

func (v NullableContext) IsSet() bool {
	return v.isSet
}

func (v *NullableContext) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContext(val *Context) *NullableContext {
	return &NullableContext{value: val, isSet: true}
}

func (v NullableContext) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContext) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


