/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.ericdriggs.reportcard.client.api;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * AppBranch
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-09-26T23:36:11.148-07:00")
public class AppBranch {
  @JsonProperty("appBranchId")
  private Integer appBranchId = null;

  @JsonProperty("appFk")
  private Integer appFk = null;

  @JsonProperty("branchFk")
  private Integer branchFk = null;

  public AppBranch appBranchId(Integer appBranchId) {
    this.appBranchId = appBranchId;
    return this;
  }

   /**
   * Get appBranchId
   * @return appBranchId
  **/
  @ApiModelProperty(value = "")
  public Integer getAppBranchId() {
    return appBranchId;
  }

  public void setAppBranchId(Integer appBranchId) {
    this.appBranchId = appBranchId;
  }

  public AppBranch appFk(Integer appFk) {
    this.appFk = appFk;
    return this;
  }

   /**
   * Get appFk
   * @return appFk
  **/
  @ApiModelProperty(value = "")
  public Integer getAppFk() {
    return appFk;
  }

  public void setAppFk(Integer appFk) {
    this.appFk = appFk;
  }

  public AppBranch branchFk(Integer branchFk) {
    this.branchFk = branchFk;
    return this;
  }

   /**
   * Get branchFk
   * @return branchFk
  **/
  @ApiModelProperty(value = "")
  public Integer getBranchFk() {
    return branchFk;
  }

  public void setBranchFk(Integer branchFk) {
    this.branchFk = branchFk;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AppBranch appBranch = (AppBranch) o;
    return Objects.equals(this.appBranchId, appBranch.appBranchId) &&
        Objects.equals(this.appFk, appBranch.appFk) &&
        Objects.equals(this.branchFk, appBranch.branchFk);
  }

  @Override
  public int hashCode() {
    return Objects.hash(appBranchId, appFk, branchFk);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AppBranch {\n");
    
    sb.append("    appBranchId: ").append(toIndentedString(appBranchId)).append("\n");
    sb.append("    appFk: ").append(toIndentedString(appFk)).append("\n");
    sb.append("    branchFk: ").append(toIndentedString(branchFk)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

