/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.ericdriggs.reportcard.client.api;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * ReportMetaData
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-09-26T23:36:11.148-07:00")
public class ReportMetaData {
  @JsonProperty("app")
  private String app = null;

  @JsonProperty("branch")
  private String branch = null;

  @JsonProperty("buildIdentifier")
  private String buildIdentifier = null;

  @JsonProperty("org")
  private String org = null;

  @JsonProperty("repo")
  private String repo = null;

  @JsonProperty("stage")
  private String stage = null;

  public ReportMetaData app(String app) {
    this.app = app;
    return this;
  }

   /**
   * Get app
   * @return app
  **/
  @ApiModelProperty(value = "")
  public String getApp() {
    return app;
  }

  public void setApp(String app) {
    this.app = app;
  }

  public ReportMetaData branch(String branch) {
    this.branch = branch;
    return this;
  }

   /**
   * Get branch
   * @return branch
  **/
  @ApiModelProperty(value = "")
  public String getBranch() {
    return branch;
  }

  public void setBranch(String branch) {
    this.branch = branch;
  }

  public ReportMetaData buildIdentifier(String buildIdentifier) {
    this.buildIdentifier = buildIdentifier;
    return this;
  }

   /**
   * Get buildIdentifier
   * @return buildIdentifier
  **/
  @ApiModelProperty(value = "")
  public String getBuildIdentifier() {
    return buildIdentifier;
  }

  public void setBuildIdentifier(String buildIdentifier) {
    this.buildIdentifier = buildIdentifier;
  }

  public ReportMetaData org(String org) {
    this.org = org;
    return this;
  }

   /**
   * Get org
   * @return org
  **/
  @ApiModelProperty(value = "")
  public String getOrg() {
    return org;
  }

  public void setOrg(String org) {
    this.org = org;
  }

  public ReportMetaData repo(String repo) {
    this.repo = repo;
    return this;
  }

   /**
   * Get repo
   * @return repo
  **/
  @ApiModelProperty(value = "")
  public String getRepo() {
    return repo;
  }

  public void setRepo(String repo) {
    this.repo = repo;
  }

  public ReportMetaData stage(String stage) {
    this.stage = stage;
    return this;
  }

   /**
   * Get stage
   * @return stage
  **/
  @ApiModelProperty(value = "")
  public String getStage() {
    return stage;
  }

  public void setStage(String stage) {
    this.stage = stage;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReportMetaData reportMetaData = (ReportMetaData) o;
    return Objects.equals(this.app, reportMetaData.app) &&
        Objects.equals(this.branch, reportMetaData.branch) &&
        Objects.equals(this.buildIdentifier, reportMetaData.buildIdentifier) &&
        Objects.equals(this.org, reportMetaData.org) &&
        Objects.equals(this.repo, reportMetaData.repo) &&
        Objects.equals(this.stage, reportMetaData.stage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(app, branch, buildIdentifier, org, repo, stage);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReportMetaData {\n");
    
    sb.append("    app: ").append(toIndentedString(app)).append("\n");
    sb.append("    branch: ").append(toIndentedString(branch)).append("\n");
    sb.append("    buildIdentifier: ").append(toIndentedString(buildIdentifier)).append("\n");
    sb.append("    org: ").append(toIndentedString(org)).append("\n");
    sb.append("    repo: ").append(toIndentedString(repo)).append("\n");
    sb.append("    stage: ").append(toIndentedString(stage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

