/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.ericdriggs.reportcard.client.api;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Stage
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-09-26T23:36:11.148-07:00")
public class Stage {
  @JsonProperty("appBranchFk")
  private Integer appBranchFk = null;

  @JsonProperty("stageId")
  private Integer stageId = null;

  @JsonProperty("stageName")
  private String stageName = null;

  public Stage appBranchFk(Integer appBranchFk) {
    this.appBranchFk = appBranchFk;
    return this;
  }

   /**
   * Get appBranchFk
   * @return appBranchFk
  **/
  @ApiModelProperty(value = "")
  public Integer getAppBranchFk() {
    return appBranchFk;
  }

  public void setAppBranchFk(Integer appBranchFk) {
    this.appBranchFk = appBranchFk;
  }

  public Stage stageId(Integer stageId) {
    this.stageId = stageId;
    return this;
  }

   /**
   * Get stageId
   * @return stageId
  **/
  @ApiModelProperty(value = "")
  public Integer getStageId() {
    return stageId;
  }

  public void setStageId(Integer stageId) {
    this.stageId = stageId;
  }

  public Stage stageName(String stageName) {
    this.stageName = stageName;
    return this;
  }

   /**
   * Get stageName
   * @return stageName
  **/
  @ApiModelProperty(value = "")
  public String getStageName() {
    return stageName;
  }

  public void setStageName(String stageName) {
    this.stageName = stageName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Stage stage = (Stage) o;
    return Objects.equals(this.appBranchFk, stage.appBranchFk) &&
        Objects.equals(this.stageId, stage.stageId) &&
        Objects.equals(this.stageName, stage.stageName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(appBranchFk, stageId, stageName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Stage {\n");
    
    sb.append("    appBranchFk: ").append(toIndentedString(appBranchFk)).append("\n");
    sb.append("    stageId: ").append(toIndentedString(stageId)).append("\n");
    sb.append("    stageName: ").append(toIndentedString(stageName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

