/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.ericdriggs.reportcard.client.api;

import java.util.Objects;
import com.ericdriggs.reportcard.client.api.TestSuite;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import org.joda.time.DateTime;

/**
 * TestResult
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-09-26T23:36:11.148-07:00")
public class TestResult {
  @JsonProperty("buildStageFk")
  private Long buildStageFk = null;

  @JsonProperty("error")
  private Integer error = null;

  @JsonProperty("failure")
  private Integer failure = null;

  @JsonProperty("hasSkip")
  private Boolean hasSkip = null;

  @JsonProperty("isSuccess")
  private Boolean isSuccess = null;

  @JsonProperty("skipped")
  private Integer skipped = null;

  @JsonProperty("testResultCreated")
  private DateTime testResultCreated = null;

  @JsonProperty("testResultId")
  private Long testResultId = null;

  @JsonProperty("testSuites")
  private List<TestSuite> testSuites = null;

  @JsonProperty("tests")
  private Integer tests = null;

  @JsonProperty("time")
  private BigDecimal time = null;

  public TestResult buildStageFk(Long buildStageFk) {
    this.buildStageFk = buildStageFk;
    return this;
  }

   /**
   * Get buildStageFk
   * @return buildStageFk
  **/
  @ApiModelProperty(value = "")
  public Long getBuildStageFk() {
    return buildStageFk;
  }

  public void setBuildStageFk(Long buildStageFk) {
    this.buildStageFk = buildStageFk;
  }

  public TestResult error(Integer error) {
    this.error = error;
    return this;
  }

   /**
   * Get error
   * @return error
  **/
  @ApiModelProperty(value = "")
  public Integer getError() {
    return error;
  }

  public void setError(Integer error) {
    this.error = error;
  }

  public TestResult failure(Integer failure) {
    this.failure = failure;
    return this;
  }

   /**
   * Get failure
   * @return failure
  **/
  @ApiModelProperty(value = "")
  public Integer getFailure() {
    return failure;
  }

  public void setFailure(Integer failure) {
    this.failure = failure;
  }

  public TestResult hasSkip(Boolean hasSkip) {
    this.hasSkip = hasSkip;
    return this;
  }

   /**
   * Get hasSkip
   * @return hasSkip
  **/
  @ApiModelProperty(value = "")
  public Boolean getHasSkip() {
    return hasSkip;
  }

  public void setHasSkip(Boolean hasSkip) {
    this.hasSkip = hasSkip;
  }

  public TestResult isSuccess(Boolean isSuccess) {
    this.isSuccess = isSuccess;
    return this;
  }

   /**
   * Get isSuccess
   * @return isSuccess
  **/
  @ApiModelProperty(value = "")
  public Boolean getIsSuccess() {
    return isSuccess;
  }

  public void setIsSuccess(Boolean isSuccess) {
    this.isSuccess = isSuccess;
  }

  public TestResult skipped(Integer skipped) {
    this.skipped = skipped;
    return this;
  }

   /**
   * Get skipped
   * @return skipped
  **/
  @ApiModelProperty(value = "")
  public Integer getSkipped() {
    return skipped;
  }

  public void setSkipped(Integer skipped) {
    this.skipped = skipped;
  }

  public TestResult testResultCreated(DateTime testResultCreated) {
    this.testResultCreated = testResultCreated;
    return this;
  }

   /**
   * Get testResultCreated
   * @return testResultCreated
  **/
  @ApiModelProperty(value = "")
  public DateTime getTestResultCreated() {
    return testResultCreated;
  }

  public void setTestResultCreated(DateTime testResultCreated) {
    this.testResultCreated = testResultCreated;
  }

  public TestResult testResultId(Long testResultId) {
    this.testResultId = testResultId;
    return this;
  }

   /**
   * Get testResultId
   * @return testResultId
  **/
  @ApiModelProperty(value = "")
  public Long getTestResultId() {
    return testResultId;
  }

  public void setTestResultId(Long testResultId) {
    this.testResultId = testResultId;
  }

  public TestResult testSuites(List<TestSuite> testSuites) {
    this.testSuites = testSuites;
    return this;
  }

  public TestResult addTestSuitesItem(TestSuite testSuitesItem) {
    if (this.testSuites == null) {
      this.testSuites = new ArrayList<TestSuite>();
    }
    this.testSuites.add(testSuitesItem);
    return this;
  }

   /**
   * Get testSuites
   * @return testSuites
  **/
  @ApiModelProperty(value = "")
  public List<TestSuite> getTestSuites() {
    return testSuites;
  }

  public void setTestSuites(List<TestSuite> testSuites) {
    this.testSuites = testSuites;
  }

  public TestResult tests(Integer tests) {
    this.tests = tests;
    return this;
  }

   /**
   * Get tests
   * @return tests
  **/
  @ApiModelProperty(value = "")
  public Integer getTests() {
    return tests;
  }

  public void setTests(Integer tests) {
    this.tests = tests;
  }

  public TestResult time(BigDecimal time) {
    this.time = time;
    return this;
  }

   /**
   * Get time
   * @return time
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getTime() {
    return time;
  }

  public void setTime(BigDecimal time) {
    this.time = time;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TestResult testResult = (TestResult) o;
    return Objects.equals(this.buildStageFk, testResult.buildStageFk) &&
        Objects.equals(this.error, testResult.error) &&
        Objects.equals(this.failure, testResult.failure) &&
        Objects.equals(this.hasSkip, testResult.hasSkip) &&
        Objects.equals(this.isSuccess, testResult.isSuccess) &&
        Objects.equals(this.skipped, testResult.skipped) &&
        Objects.equals(this.testResultCreated, testResult.testResultCreated) &&
        Objects.equals(this.testResultId, testResult.testResultId) &&
        Objects.equals(this.testSuites, testResult.testSuites) &&
        Objects.equals(this.tests, testResult.tests) &&
        Objects.equals(this.time, testResult.time);
  }

  @Override
  public int hashCode() {
    return Objects.hash(buildStageFk, error, failure, hasSkip, isSuccess, skipped, testResultCreated, testResultId, testSuites, tests, time);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TestResult {\n");
    
    sb.append("    buildStageFk: ").append(toIndentedString(buildStageFk)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("    failure: ").append(toIndentedString(failure)).append("\n");
    sb.append("    hasSkip: ").append(toIndentedString(hasSkip)).append("\n");
    sb.append("    isSuccess: ").append(toIndentedString(isSuccess)).append("\n");
    sb.append("    skipped: ").append(toIndentedString(skipped)).append("\n");
    sb.append("    testResultCreated: ").append(toIndentedString(testResultCreated)).append("\n");
    sb.append("    testResultId: ").append(toIndentedString(testResultId)).append("\n");
    sb.append("    testSuites: ").append(toIndentedString(testSuites)).append("\n");
    sb.append("    tests: ").append(toIndentedString(tests)).append("\n");
    sb.append("    time: ").append(toIndentedString(time)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

